version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "08:30"
      timezone: "Europe/Rome"
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      time: "08:30"
      timezone: "Europe/Rome"
    open-pull-requests-limit: 10
