inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - .git/**/*
    - .github/**/*
    - gemfiles/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
