language: ruby

rvm:
  - 2.6.5

services:
  - redis-server

addons:
  apt:
    update: true
    packages:
      - imagemagick
      - libmagic-dev
      - libreoffice
      - tesseract-ocr

cache:
  bundler: true

before_install:
  # tika
  - wget --quiet https://apache.osuosl.org/tika/tika-app-1.24.jar
  - mv tika-app-1.24.jar $HOME/bin/tika-app.jar
  - echo $'#!/bin/sh\n\nARGS="$@"\n\n[ $# -eq 0 ] && ARGS="--help"\n\nexec java -jar $HOME/bin/tika-app.jar $ARGS\n' > $HOME/bin/tika
  - cat $HOME/bin/tika
  - chmod +x $HOME/bin/tika

  # wkhtmltopdf (with qt)
  - wget --quiet https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb
  - dpkg -x wkhtmltox_0.12.5-1.xenial_amd64.deb tmp-wkhtmtopdf
  - mv tmp-wkhtmtopdf/usr/local/bin/wkhtmltopdf $HOME/bin/wkhtmltopdf
  - rm -rf wkhtmltox_0.12.5-1.xenial_amd64.deb tmp-wkhtmtopdf

  # Show versions of all executables
  - convert --version
  - libreoffice --version
  - tesseract --version
  - tika --version
  - wkhtmltopdf --version

script:
  - bundle exec rspec
