dist: bionic
os: linux

language: ruby

rvm:
  - 2.6.5

jobs:
  include:
   - dist: xenial
   - dist: bionic
   - dist: focal

services:
  - redis

addons:
  apt:
    update: true
    packages:
      - imagemagick
      - libmagic-dev
      - libreoffice
      - tesseract-ocr

cache:
  bundler: true

before_install:
  # tika
  - TIKA_VERSION=1.25
  - wget --quiet https://archive.apache.org/dist/tika/tika-app-${TIKA_VERSION}.jar -O $HOME/bin/tika-app.jar
  - echo $'#!/bin/sh\n\nARGS="$@"\n\n[ $# -eq 0 ] && ARGS="--help"\n\nexec java -jar $HOME/bin/tika-app.jar $ARGS\n' > $HOME/bin/tika
  - cat $HOME/bin/tika
  - chmod +x $HOME/bin/tika

  # wkhtmltopdf (with qt)
  - WKHTMLTOPDF_VERSION=0.12.3
  - wget --quiet https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/${WKHTMLTOPDF_VERSION}/wkhtmltox-${WKHTMLTOPDF_VERSION}_linux-generic-amd64.tar.xz -O wkhtmltox.tar.xz
  - tar -xf wkhtmltox.tar.xz
  - mv wkhtmltox/bin/wkhtmltopdf $HOME/bin/wkhtmltopdf
  - rm -rf wkhtmltox wkhtmltox.tar.xz

  # Show versions of all executables
  - convert --version
  - libreoffice --version
  - tesseract --version
  - tika --version
  - wkhtmltopdf --version

script:
  - bundle exec rspec
