#
# Colore's primary configuration file
#

# Where the documents are stored
storage_directory: storage

# Legacy (heathen) method support.
# legacy_url_base will overwrite local URL base to allow proxy navigation;
# this is needed 'cos the full URL is returned in the legacy convert JSON.
#legacy_url_base: http://localhost:9240/
# number of days to keep converted legacy files
legacy_purge_days: 2

# Sidekiq configuration settings - which redis to use and namespace
redis:
  :url: <%= ENV.fetch('REDIS_URL', 'redis://localhost:6379/4') %>
  :namespace: colore

# Conversion processes log
conversion_log: log/converter.log

# Errors log
error_log: log/error.log

# If set, will run these executables rather than looking into PATH
convert_path: <%= ENV['CONVERT_PATH'] %>
libreoffice_path: <%= ENV['LIBREOFFICE_PATH'] %>
tesseract_path: <%= ENV['TESSERACT_PATH'] %>
tika_path: <%= ENV['TIKA_PATH'] %>
wkhtmltopdf_path: <%= ENV['WKHTMLTOPDF_PATH'] %>

# Other settings
tika_config_directory: <%= ENV['TIKA_CONFIG_DIRECTORY'] %>
wkhtmltopdf_params: '-d 100 --encoding UTF-8'
tesseract_available_languages: <%= ENV['TESSERACT_AVAILABLE_LANGUAGES'] %>
