name: RuboCop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest

    env:
      BUNDLE_GEMFILE: gemfiles/rubocop.gemfile

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.4
          bundler-cache: true
          rubygems: latest
      - name: RuboCop
        run: |
          bundle exec rubocop --format github
