name: YARD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  yard:
    name: YARD
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6.10'
        bundler-cache: false
        rubygems: latest
    - name: Lint YARD documentation
      run: |
        gem install yard
        yard doc --fail-on-warning --no-output --no-progress
